### ISSUE TITLE
注入权限验证配置错误

### ISSUE THREAD

**Issue by Icacls** [xuqingkuang/wx-sdk-ts#1]
main.js:1 ERROR TypeError: o.config is not a function(…)

调用config验证配置信息出现这个错误，请问要怎么处理呢

**Comment by xuqingkuang** [comment]
大哥，这个错误跟这项目有关系么？

从项目角度而言，最好也给出一些上下文代码，如果是在调用微信 SDK 的时候出现的，加个断点看看一下 o 是什么，Call stack 在哪里。
